#!/bin/tcsh

clear

# Define some variables
setenv UNITY_HOME /Applications/Unity5.6.0p1/Unity.app/Contents/MacOS
setenv AUTO_HOME /Users/mohammed/Projects/auto
setenv PROJECT_PATH /Users/mohammed/Projects/auto/iap
setenv PKG_PATH /Users/mohammed/Projects/auto/pkg/iap.unitypackage

# Clean unity project
echo "(1) ---------- Cleaning up"
echo ${PROJECT_PATH}
echo
cd ${PROJECT_PATH}
git checkout . > /dev/null
git clean -fdx . > /dev/null

# Import IAP package
echo "(2) ---------- Importing IAP package"
echo ${UNITY_HOME}/Unity -batchMode -projectPath ${PROJECT_PATH} -importPackage ${PKG_PATH} -logFile ${AUTO_HOME}/import.log
echo
if ($1 == "-i") then 
   ${UNITY_HOME}/Unity -projectPath ${PROJECT_PATH} -importPackage ${PKG_PATH} -logFile ${AUTO_HOME}/import.log
else 
   ${UNITY_HOME}/Unity -batchMode -projectPath ${PROJECT_PATH} -importPackage ${PKG_PATH} -logFile ${AUTO_HOME}/import.log
endif
cp ${AUTO_HOME}/src/IAPAuto_fb.cs ${PROJECT_PATH}/Assets/Plugins/UnityPurchasing/script/IAPAuto.cs
cp ${AUTO_HOME}/src/AutoBuilder.cs ${PROJECT_PATH}/Assets/Plugins/UnityPurchasing/Editor

# Build unity project
echo "(3) ---------- Building unity"
echo ${UNITY_HOME}/Unity -batchMode -quit -projectPath ${PROJECT_PATH} -executeMethod AutoBuilder.PerformFacebookWebglBuild -logFile ${AUTO_HOME}/build.log
echo
if ($1 == "-i") then 
   ${UNITY_HOME}/Unity -projectPath ${PROJECT_PATH} -executeMethod AutoBuilder.PerformFacebookWebglBuild -logFile ${AUTO_HOME}/build.log
else 
   ${UNITY_HOME}/Unity -batchMode -quit -projectPath ${PROJECT_PATH} -executeMethod AutoBuilder.PerformFacebookWebglBuild -logFile ${AUTO_HOME}/build.log
endif

# Create facebook package
echo "(4) ---------- Create facebook package"
echo 7z a ${PROJECT_PATH}/Builds/facebook/facebook_webgl.7z ${PROJECT_PATH}/Builds/facebook
echo
7z a ${PROJECT_PATH}/Builds/facebook/facebook_webgl.7z ${PROJECT_PATH}/Builds/facebook

# Upload to facebook ?