#!/bin/tcsh

clear

# Set unity version
if ($2 != "") then 
   setenv UNITY_VERSION $2
else
   setenv UNITY_VERSION Unity201710f3
endif

# Define some variables
setenv UNITY_HOME /Applications/${UNITY_VERSION}/Unity.app/Contents/MacOS
setenv AUTO_HOME /Users/mohammed/Projects/auto

if ("${UNITY_VERSION}" == "Unity553p2") then 
   setenv PROJECT_PATH /Users/mohammed/Projects/auto/iap/${UNITY_VERSION}/google
else 
   setenv PROJECT_PATH /Users/mohammed/Projects/auto/iap/${UNITY_VERSION}
endif

setenv PKG_PATH /Users/mohammed/Projects/auto/pkg/iap.unitypackage
setenv BUNDLE_ID com.eight.bit.avenue.amorcam
setenv ACTIVITY com.unity3d.player.UnityPlayerActivity

# Clean unity project
echo "(1) ---------- Cleaning up"
echo ${PROJECT_PATH}
echo
cd ${PROJECT_PATH}
git checkout . > /dev/null
git clean -fdx . > /dev/null

# Import IAP package
echo "(2) ---------- Importing IAP package"
echo ${UNITY_HOME}/Unity -batchMode -projectPath ${PROJECT_PATH} -importPackage ${PKG_PATH} -logFile ${AUTO_HOME}/import.log
echo
if ($1 == "i") then 
   ${UNITY_HOME}/Unity -projectPath ${PROJECT_PATH} -importPackage ${PKG_PATH} -logFile ${AUTO_HOME}/import.log
else 
   ${UNITY_HOME}/Unity -batchMode -projectPath ${PROJECT_PATH} -importPackage ${PKG_PATH} -logFile ${AUTO_HOME}/import.log
endif
cp ${AUTO_HOME}/src/IAPDemo_fr.cs ${PROJECT_PATH}/Assets/Plugins/UnityPurchasing/script/IAPDemo.cs
cp ${AUTO_HOME}/src/BillingMode_google.json ${PROJECT_PATH}/Assets/Plugins/UnityPurchasing/Resources/BillingMode.json
cp ${AUTO_HOME}/src/AutoBuilder.cs ${PROJECT_PATH}/Assets/Plugins/UnityPurchasing/Editor

# Build unity project
echo "(3) ---------- Building unity"
echo ${UNITY_HOME}/Unity -batchMode -quit -projectPath ${PROJECT_PATH} -executeMethod AutoBuilder.PerformFrenchLocaleBuild -logFile ${AUTO_HOME}/build.log
echo
if ($1 == "i") then 
   ${UNITY_HOME}/Unity -projectPath ${PROJECT_PATH} -executeMethod AutoBuilder.PerformFrenchLocaleBuild -logFile ${AUTO_HOME}/build.log
else 
   ${UNITY_HOME}/Unity -batchMode -quit -projectPath ${PROJECT_PATH} -executeMethod AutoBuilder.PerformFrenchLocaleBuild -logFile ${AUTO_HOME}/build.log
endif

# Uninstall APK
echo "(4) ---------- Uninstall APK"
echo adb uninstall ${BUNDLE_ID}
echo
adb uninstall ${BUNDLE_ID}

# Install APK
echo "(5) ---------- Install APK"
echo adb install ${PROJECT_PATH}/Builds/fr_locale.apk
echo
adb install ${PROJECT_PATH}/Builds/fr_locale.apk

# Launch application
echo "(6) ---------- Launching IAPAuto"
echo adb shell am start -n ${BUNDLE_ID}/${ACTIVITY}
echo
adb shell am start -n ${BUNDLE_ID}/${ACTIVITY}

# Quit application
sleep 15
echo "(7) ---------- Closing IAPAuto"
echo adb shell pm clear ${BUNDLE_ID}
echo
if ($3 != "") then
   adb shell pm clear ${BUNDLE_ID} 
endif

