#!/bin/tcsh

clear

# Set unity version
if ($2 != "") then 
   setenv UNITY_VERSION $2
else
   setenv UNITY_VERSION Unity201710f3
endif

# Define some variables
setenv UNITY_HOME /Applications/${UNITY_VERSION}/Unity.app/Contents/MacOS
setenv AUTO_HOME /Users/mohammed/Projects/auto
setenv PROJECT_PATH /Users/mohammed/Projects/auto/iap/${UNITY_VERSION}
setenv PKG_PATH /Users/mohammed/Projects/auto/pkg/iap.unitypackage
setenv BUNDLE_ID com.unity3d.unityiap.demo
setenv DEVICE_ID 654d380ec156801d17dd698928167e766f1d60eb

# Clean unity project
echo "(1) ---------- Cleaning up"
echo ${PROJECT_PATH}
echo
cd ${PROJECT_PATH}
git checkout . > /dev/null
git clean -fdx . > /dev/null

# Import IAP package
echo "(2) ---------- Importing IAP package"
echo ${UNITY_HOME}/Unity -batchMode -projectPath ${PROJECT_PATH} -importPackage ${PKG_PATH} -logFile ${AUTO_HOME}/import.log
echo
if ($1 == "i") then 
   ${UNITY_HOME}/Unity -projectPath ${PROJECT_PATH} -importPackage ${PKG_PATH} -logFile ${AUTO_HOME}/import.log
else 
   ${UNITY_HOME}/Unity -batchMode -projectPath ${PROJECT_PATH} -importPackage ${PKG_PATH} -logFile ${AUTO_HOME}/import.log
endif
cp ${AUTO_HOME}/src/IAPAuto_ios_promote_hide_order.cs ${PROJECT_PATH}/Assets/Plugins/UnityPurchasing/script/IAPAuto.cs
cp ${AUTO_HOME}/src/AutoBuilder.cs ${PROJECT_PATH}/Assets/Plugins/UnityPurchasing/Editor

# Build unity project
echo "(3) ---------- Building unity"
echo ${UNITY_HOME}/Unity -batchMode -quit -projectPath ${PROJECT_PATH} -executeMethod AutoBuilder.PerformiOSBuild -logFile ${AUTO_HOME}/build.log
echo
if ($1 == "i") then 
   ${UNITY_HOME}/Unity -projectPath ${PROJECT_PATH} -executeMethod AutoBuilder.PerformiOSBuild -logFile ${AUTO_HOME}/build.log
else 
   ${UNITY_HOME}/Unity -batchMode -quit -projectPath ${PROJECT_PATH} -executeMethod AutoBuilder.PerformiOSBuild -logFile ${AUTO_HOME}/build.log
endif

# Deploy app to device
echo "(4) ---------- Launch application"
echo xcodebuild test -destination "platform=iOS,id=${DEVICE_ID}" -scheme Unity-iPhone -project ${PROJECT_PATH}/Builds/iOS/Unity-iPhone.xcodeproj
xcodebuild test -destination "platform=iOS,id=${DEVICE_ID}" -scheme Unity-iPhone -project ${PROJECT_PATH}/Builds/iOS/Unity-iPhone.xcodeproj




