#!/bin/tcsh

clear

# Define some variables
setenv UNITY_HOME /Applications/Unity5.6.0p1/Unity.app/Contents/MacOS
setenv AUTO_HOME /Users/mohammed/Projects/auto
setenv PROJECT_PATH /Users/mohammed/Projects/auto/iap
setenv PKG_PATH /Users/mohammed/Projects/auto/pkg/iap.unitypackage

# Clean unity project
echo "(1) ---------- Cleaning up"
echo ${PROJECT_PATH}
echo
cd ${PROJECT_PATH}
git checkout . > /dev/null
git clean -fdx . > /dev/null

# Import IAP package
echo "(2) ---------- Importing IAP package"
echo ${UNITY_HOME}/Unity -batchMode -projectPath ${PROJECT_PATH} -importPackage ${PKG_PATH} -logFile ${AUTO_HOME}/import.log
echo
if ($1 == "-i") then 
   ${UNITY_HOME}/Unity -projectPath ${PROJECT_PATH} -importPackage ${PKG_PATH} -logFile ${AUTO_HOME}/import.log
else 
   ${UNITY_HOME}/Unity -batchMode -projectPath ${PROJECT_PATH} -importPackage ${PKG_PATH} -logFile ${AUTO_HOME}/import.log
endif
cp ${AUTO_HOME}/src/IAPAuto.cs ${PROJECT_PATH}/Assets/Plugins/UnityPurchasing/script
cp ${AUTO_HOME}/src/UpdateBundleID.cs ${PROJECT_PATH}/Assets/Plugins/UnityPurchasing/Editor
cp ${AUTO_HOME}/src/AutoBuilder.cs ${PROJECT_PATH}/Assets/Plugins/UnityPurchasing/Editor

# Build unity project
echo "(3) ---------- Building unity"
echo ${UNITY_HOME}/Unity -batchMode -quit -projectPath ${PROJECT_PATH} -executeMethod AutoBuilder.PerformMacBuild -logFile ${AUTO_HOME}/build.log
echo
if ($1 == "-i") then 
   ${UNITY_HOME}/Unity -projectPath ${PROJECT_PATH} -executeMethod AutoBuilder.PerformMacBuild -logFile ${AUTO_HOME}/build.log
else 
   ${UNITY_HOME}/Unity -batchMode -quit -projectPath ${PROJECT_PATH} -executeMethod AutoBuilder.PerformMacBuild -logFile ${AUTO_HOME}/build.log
endif

# Launch application
echo "(4) ---------- Launching IAPAuto"
echo open -a ${PROJECT_PATH}/Builds/OSX-Universal/iap_mac.app $1
echo
open -a ${PROJECT_PATH}/Builds/OSX-Universal/iap_mac.app $1

# Quit application
sleep 5
echo "(5) ---------- Closing IAPAuto"
echo osascript -e 'quit app "IAPAuto"'
echo
osascript -e 'quit app "IAPAuto"'

