#!/bin/tcsh

clear

# Set unity version
if ($2 != "") then 
   setenv UNITY_VERSION $2
else
   setenv UNITY_VERSION Unity201710f3
endif

# Define some variables
setenv UNITY_HOME /Applications/${UNITY_VERSION}/Unity.app/Contents/MacOS
setenv AUTO_HOME ${HOME}/Projects/auto
setenv PROJECT_PATH ${HOME}/Projects/auto/iap/${UNITY_VERSION}
setenv PKG_PATH ${HOME}/Projects/auto/pkg/iap.unitypackage

# Clean unity project
echo "(1) ---------- Cleaning up"
echo ${PROJECT_PATH}
echo
cd ${PROJECT_PATH}
git checkout . > /dev/null
git clean -fdx . > /dev/null

# Import IAP package
echo "(2) ---------- Importing IAP package"
echo ${UNITY_HOME}/Unity -batchMode -projectPath ${PROJECT_PATH} -importPackage ${PKG_PATH} -logFile ${AUTO_HOME}/import.log
echo
if ($1 == "i") then 
   ${UNITY_HOME}/Unity -projectPath ${PROJECT_PATH} -importPackage ${PKG_PATH} -logFile ${AUTO_HOME}/import.log
else 
   ${UNITY_HOME}/Unity -batchMode -projectPath ${PROJECT_PATH} -importPackage ${PKG_PATH} -logFile ${AUTO_HOME}/import.log
endif
cp ${AUTO_HOME}/src/IAPDemo_ci.cs ${PROJECT_PATH}/Assets/Plugins/UnityPurchasing/script/IAPDemo.cs
cp ${AUTO_HOME}/src/UpdateBundleID.cs ${PROJECT_PATH}/Assets/Plugins/UnityPurchasing/Editor
cp ${AUTO_HOME}/src/AutoBuilder.cs ${PROJECT_PATH}/Assets/Plugins/UnityPurchasing/Editor

# Build unity project
echo "(3) ---------- Building unity"
echo ${UNITY_HOME}/Unity -batchMode -quit -projectPath ${PROJECT_PATH} -executeMethod AutoBuilder.PerformMacBuild -logFile ${AUTO_HOME}/build.log
echo
if ($1 == "i") then 
   ${UNITY_HOME}/Unity -projectPath ${PROJECT_PATH} -executeMethod AutoBuilder.PerformMacBuild -logFile ${AUTO_HOME}/build.log
else 
   ${UNITY_HOME}/Unity -batchMode -quit -projectPath ${PROJECT_PATH} -executeMethod AutoBuilder.PerformMacBuild -logFile ${AUTO_HOME}/build.log
endif

# Start the server
echo "(4) ---------- Starting python server"
setenv x `ps -ef | grep server.py | grep 9999 | wc -l`
rm ${AUTO_HOME}/src/result.json
if ($x == 0) then
  cd ${AUTO_HOME}/src
  python server.py 9999 &
endif

# Launch application
echo "(5) ---------- Launching IAPDemo"
echo open -a ${PROJECT_PATH}/Builds/OSX-Universal/${UNITY_VERSION}_mac.app
echo
open -a ${PROJECT_PATH}/Builds/OSX-Universal/${UNITY_VERSION}_mac.app

# Quit application
sleep 5
echo "(6) ---------- Closing IAPDemo"
echo osascript -e 'quit app "IAPDemo"'
echo
if ($3 != "") then
   osascript -e 'quit app "IAPDemo"'
endif

# Assertion
echo "(7) ---------- Assertion"
echo diff ${AUTO_HOME}/src/result.json ${AUTO_HOME}/src/mac_result.json
diff ${AUTO_HOME}/src/result.json ${AUTO_HOME}/src/mac_result.json
if ($status != 0) then
  echo "Assertion failed"
  exit 1
endif
