#!/usr/bin/bash

clear

# Define some variables
UNITY_HOME="/c/Program Files/Unity/Editor"
AUTO_HOME="/c/Users/mohammed/Documents/auto"
PROJECT_PATH="/c/Users/mohammed/Documents/auto/iap"
PKG_PATH="/c/Users/mohammed/Documents/auto/pkg/iap.unitypackage"

# Clean unity project
echo "(1) ---------- Cleaning up"
echo ${PROJECT_PATH}
echo
cd "${PROJECT_PATH}"
git checkout . > /dev/null
git clean -fdx . > /dev/null

# Import IAP package
echo "(2) ---------- Importing IAP package"
echo ${UNITY_HOME}/Unity -batchMode -projectPath ${PROJECT_PATH} -importPackage ${PKG_PATH} -logFile ${AUTO_HOME}/import.log
echo
if ($1 == "-i") then 
   "${UNITY_HOME}"/Unity -projectPath "${PROJECT_PATH}" -importPackage "${PKG_PATH}" -logFile "${AUTO_HOME}"/import.log
else 
   "${UNITY_HOME}"/Unity -batchMode -projectPath "${PROJECT_PATH}" -importPackage "${PKG_PATH}" -logFile "${AUTO_HOME}"/import.log
endif
cp "${AUTO_HOME}"/src/IAPAuto_win.cs "${PROJECT_PATH}"/Assets/Plugins/UnityPurchasing/script/IAPAuto.cs
cp "${AUTO_HOME}"/src/AutoBuilder.cs "${PROJECT_PATH}"/Assets/Plugins/UnityPurchasing/Editor

# Build unity project
echo "(3) ---------- Building unity"
echo ${UNITY_HOME}/Unity -batchMode -quit -projectPath ${PROJECT_PATH} -executeMethod AutoBuilder.PerformWindowsUniversalBuild -logFile ${AUTO_HOME}/build.log
echo
if ($1 == "-i") then 
   "${UNITY_HOME}"/Unity -projectPath "${PROJECT_PATH}" -executeMethod AutoBuilder.PerformWindowsUniversalBuild -logFile ${AUTO_HOME}/build.log
else 
   "${UNITY_HOME}"/Unity -batchMode -quit -projectPath "${PROJECT_PATH}" -executeMethod AutoBuilder.PerformWindowsUniversalBuild -logFile ${AUTO_HOME}/build.log
endif

# Build VS project
# cp cPackage.appxmanifest "${PROJECT_PATH}"/Builds/WindowsUniversal/IAPAuto
# "${AUTO_HOME}"/run/nuget.exe restore "${PROJECT_PATH}"/Builds/WindowsUniversal/IAPAuto.sln
# "/c/program files (x86)/MSBuild/14.0/bin/msbuild.exe" "${PROJECT_PATH}"/Builds/WindowsUniversal/IAPAuto.sln /p:Configuration=Debug /p:Platform=x64

# nuget restore project.json -NonInteractive -Source https://api.nuget.org/v3/index.json

# Launch application





